### ISSUE TITLE
AERORP is possibly quite wrong.

### ISSUE THREAD

**Issue by Zaretto** [MatthewA4/F-4X#4]
https://github.com/MatthewA4/F-4X/blob/b4b36254f3ac1f9f5e90a7f1294e79283aa331c0/F-4S-fdm.xml#L55

The AERORP.X looks quite wrong to me. Normally this would be a position on the wing, measured from the reference point (usually around the tip of nose, but the I can't find the definition of the reference point in the report) - so I'm assuming (and could be wrong) that it will be around the nose.

From AFWAL-TR-80-3141

Xref is 31% cbar
Actual CG is 29.3% cbar

To figure out the actual position in meters you need to figure out where the MAC sits on the wing, then move along the specified percentage (as above, i.e. 31%) and then you have to figure out the distance from the reference point in meters of that point, probably using a 3 view.

illustration of how I find the X position of a %MAC - based on how I did this for the Tornado, although this was for 25%MAC the theory is the same.

![image](https://user-images.githubusercontent.com/2045654/42417534-03aede66-828d-11e8-8143-a6633699d466.png)

**Comment by MatthewA4** [comment]
I will review that, thanks.

**Comment by MatthewA4** [comment]
![image](https://user-images.githubusercontent.com/18086861/42421839-ec340a8c-8290-11e8-9a3a-6e8c13a885f8.png)

3D cursor position is where the AERORP is as of current commit. I suspect it is not far enough back.

**Comment by Zaretto** [comment]
In terms of the 3d model; probably. but that's not the same as the aero model. 

For the aero model you *have* to use the same coordinate system reference point as the report[1] as this is where all of the moments have been measured from for the aerodata that you are using. 

Effectively if you move the aircraft so that the tip of the nose is on the green line (at 0,0,0) then that's where your aerorp is for the aero model.

----------------------------------------------------------
[1] or adjust the reference frame for all of the moment coefficients, which isn't easy.

**Comment by MatthewA4** [comment]
![image](https://user-images.githubusercontent.com/18086861/42422024-f7cc46cc-8293-11e8-9d85-e33d7f182d08.png)
(ignore the line after the wing, used that just to figure out the length of the MAC line)
Adjustments made, not yet pushed.

**Comment by MatthewA4** [comment]
I adjusted the fuel tank positions as well, it flips on itself at high angular velocity on spawn. :|

Because I accidentally moved the CG aft instead of forward :(

**Comment by Zaretto** [comment]
are you using the MRC figures from the report or calculating it from the black lines inboard and outboard?

**Comment by MatthewA4** [comment]
I figured out the mean chord position by adding up the chord length of the root and tip, and dividing it in half.

I meant the location of of the mean chord, sorry.

**Comment by Zaretto** [comment]
That's not going to work as you have to calculate it differently[1]; just use the figure from the report (16.04 feet).
![image](https://user-images.githubusercontent.com/2045654/42423211-043be242-82f7-11e8-8007-100119613859.png)

------------------------
[1] http://www.airfieldmodels.com/information_source/math_and_science_of_model_aircraft/formulas/mean_aerodynamic_chord.htm

**Comment by MatthewA4** [comment]
I made the necessary adjustments, now something is not quite right with the pitch, as it will not exceed +9 AoA in flight.

**Comment by MatthewA4** [comment]
Also, the reason why it rolled on-top of itself was due to out of place rear gears, and no tail contact point, also corrected.

https://github.com/MatthewA4/F-4X/commit/b091caca9c2fb1debcecab6f133e04a0836dea90
